server:
  port: 8081
security:
  oauth2:
    client:
      clientId: resource.client
      clientSecret: password
    resource:
      user-info-uri: http://authz-server:8080/oauth/userinfo
      token-info-uri: http://authz-server:8080/oauth/check_token






